### PR TITLE
Add support for mips32

### PR DESCRIPTION
**Pull request by hguandl**
Routers are ideal devices to run godns. Their platforms are often mips or mipsle. However, the cross-compiled binary for mips32 does not support CGO, so that the program would have x509 error when using https. One solution is to manually add the certificate chain of dnsapi.cn to the codes. Here are the [reference](http://yangzhe1991.org/blog/2013/12/golang-https-without-cgo/) and the [pre-compiled binary](https://github.com/TimothyYe/godns/files/1226787/godns-mips32-1.1.tar.gz).

### CODE REVIEW

**Comment by TimothyYe** [comment]
Hi @hguandl ,
As you mentioned mips32 doesn't support CGO, have you ever tried to compile this project with this:
CGO_ENABLED=0 GOOS=linux  GOARCH=mips32  go build

**Comment by hguandl** [comment]
Yes. I can compile in this way. But if I use the compiled binary, it tells me that there is an error "x509: failed to load system roots and no roots provided". I searched for the solution and found out that because using https requires CGO, the program went wrong. So in this pull I add the certificate to the source code to avoid this. The concerned passage is this: http://yangzhe1991.org/blog/2013/12/golang-https-without-cgo/

**Comment by TimothyYe** [comment]
Hi @hguandl,
Have you tested the compatibility for this modification? 
Does it still compatible with Linux OS?

**Comment by hguandl** [comment]
I've tested it on CentOS 6 x32 and macOS Sierra. It works well on both platforms. I think the modification only skips the procedures which require CGO and use another way to finish them. However, there is a potential problem about the certificate, for the period of validity is limited. The current certificate is valid until Tue, 10 Jul 2018 23:59:59 UTC ([SSL Server Test](https://www.ssllabs.com/ssltest/analyze.html?d=dnsapi.cn)). We need to update the certificate and compile the program from time to time. In conclusion, this is only an alternative for embedded OS. Keeping it as a branch is OK.

**Comment by TimothyYe** [comment]
Thanks hguandl!

**Pull request merged**
